"""Best-effort API reporting contracts after execution filesystem outcomes."""

from tests.review.tasks import _execution_contract_scenarios as scenarios


test_post_execution_log_failure_is_swallowed = scenarios.test_post_execution_log_failure_is_swallowed
test_patch_completed_log_failure_is_swallowed = scenarios.test_patch_completed_log_failure_is_swallowed
test_patch_failed_log_failure_is_swallowed = scenarios.test_patch_failed_log_failure_is_swallowed
test_patch_proposal_state_failed_report_failure_is_swallowed = scenarios.test_patch_proposal_state_failed_report_failure_is_swallowed
test_progress_post_failure_on_success_path_is_swallowed = scenarios.test_progress_post_failure_on_success_path_is_swallowed
test_progress_post_failure_on_failure_path_is_swallowed = scenarios.test_progress_post_failure_on_failure_path_is_swallowed
test_executed_state_patch_5xx_does_not_fail_proposal = scenarios.test_executed_state_patch_5xx_does_not_fail_proposal
