"""phaze-6bkk: the AGENT-side CUE write -- containment, versioning, and off-loop I/O.

The write moved here from ``routers/cue.py`` because the api container mounts no media (DIST-01),
so its ``write_cue_file`` call raised ``FileNotFoundError`` for every CUE sheet, always.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any
from unittest.mock import AsyncMock, MagicMock, patch
import uuid

import pytest

from phaze.tasks.cue_write import write_cue_sheet


if TYPE_CHECKING:
    from pathlib import Path


_CUE = 'REM COMMENT "Generated by Phaze"\nFILE "<set-01>.mp3" MP3\n  TRACK 01 AUDIO\n    INDEX 01 00:00:00\n'


def _kwargs(audio_path: Path) -> dict[str, Any]:
    return {
        "file_id": str(uuid.uuid4()),
        "tracklist_id": str(uuid.uuid4()),
        "agent_id": "fileserver-01",
        "audio_path": str(audio_path),
        "content": _CUE,
    }


def _agent_settings(scan_roots: list[str]) -> Any:
    """A stand-in AgentSettings carrying only what the task reads.

    ``spec=`` matters: the task gates on ``isinstance(cfg, AgentSettings)`` (a control-role config
    has no ``scan_roots``), and only a spec'd mock satisfies that.
    """
    from phaze.config import AgentSettings

    cfg = MagicMock(spec=AgentSettings)
    cfg.scan_roots = scan_roots
    return cfg


class TestWriteCueSheetTask:
    @pytest.mark.asyncio
    async def test_writes_the_cue_beside_the_audio_file(self, tmp_path: Path) -> None:
        audio = tmp_path / "<set-01>.mp3"
        audio.write_text("fake audio")

        with patch("phaze.tasks.cue_write.get_settings", return_value=_agent_settings([str(tmp_path)])):
            result = await write_cue_sheet({}, **_kwargs(audio))

        written = tmp_path / "<set-01>.cue"
        assert written.exists()
        assert written.read_text(encoding="utf-8-sig") == _CUE
        assert result["cue_filename"] == "<set-01>.cue"
        assert result["cue_version"] == 1

    @pytest.mark.asyncio
    async def test_regenerate_writes_the_next_version(self, tmp_path: Path) -> None:
        """phaze-9dwb: the version comes back from the SAME scan that picked the path.

        No second ``exists()`` + ``iterdir()`` sweep is needed to learn it -- which is what
        ``routers/cue.py::_get_cue_version`` used to do, on the api event loop.
        """
        audio = tmp_path / "<set-01>.mp3"
        audio.write_text("fake audio")

        with patch("phaze.tasks.cue_write.get_settings", return_value=_agent_settings([str(tmp_path)])):
            first = await write_cue_sheet({}, **_kwargs(audio))
            second = await write_cue_sheet({}, **_kwargs(audio))

        assert (first["cue_filename"], first["cue_version"]) == ("<set-01>.cue", 1)
        assert (second["cue_filename"], second["cue_version"]) == ("<set-01>.v2.cue", 2)

    @pytest.mark.asyncio
    async def test_path_outside_scan_roots_is_refused(self, tmp_path: Path) -> None:
        """The audio path is agent-REPORTED data, so it is containment-checked before any open().

        Checked here rather than on the control plane because only the machine holding the mount can
        resolve symlinks honestly (T-26-11-S1).
        """
        outside = tmp_path / "outside"
        outside.mkdir()
        roots = tmp_path / "roots"
        roots.mkdir()
        audio = outside / "<set-01>.mp3"
        audio.write_text("fake audio")

        with (
            patch("phaze.tasks.cue_write.get_settings", return_value=_agent_settings([str(roots)])),
            pytest.raises(ValueError, match="escapes all scan_roots"),
        ):
            await write_cue_sheet({}, **_kwargs(audio))

        assert not (outside / "<set-01>.cue").exists()

    @pytest.mark.asyncio
    async def test_no_scan_roots_refuses_everything(self, tmp_path: Path) -> None:
        """An empty root list matches nothing -- 'refuse', never 'allow' (services/containment.py)."""
        audio = tmp_path / "<set-01>.mp3"
        audio.write_text("fake audio")

        with (
            patch("phaze.tasks.cue_write.get_settings", return_value=_agent_settings([])),
            pytest.raises(ValueError, match="escapes all scan_roots"),
        ):
            await write_cue_sheet({}, **_kwargs(audio))

    @pytest.mark.asyncio
    async def test_disk_work_runs_off_the_event_loop(self, tmp_path: Path) -> None:
        """phaze-9dwb: the version scan + create + write are ONE offload, never on the loop.

        The agent's loop runs the Phase-46 liveness heartbeat; an ``iterdir()`` over a concert-set
        directory (thousands of siblings) blocks it for ms even on healthy local disk, and
        indefinitely on a hung mount.
        """
        audio = tmp_path / "<set-01>.mp3"
        audio.write_text("fake audio")

        with (
            patch("phaze.tasks.cue_write.get_settings", return_value=_agent_settings([str(tmp_path)])),
            patch("phaze.tasks.cue_write.asyncio.to_thread", new_callable=AsyncMock) as to_thread,
        ):
            to_thread.return_value = (tmp_path / "<set-01>.cue", 1)
            await write_cue_sheet({}, **_kwargs(audio))

        to_thread.assert_awaited_once()
        assert to_thread.await_args.args[0].__name__ == "_write_sync"
