"""Execution audit healing and non-reconstructible terminal-token contracts."""

from tests.review.tasks import _execution_contract_scenarios as scenarios


test_lost_completion_token_on_success_path_raises_for_saq_replay = scenarios.test_lost_completion_token_on_success_path_raises_for_saq_replay
test_lost_completion_token_does_not_mark_the_proposal_failed = scenarios.test_lost_completion_token_does_not_mark_the_proposal_failed
test_lost_completion_token_on_failure_path_also_raises = scenarios.test_lost_completion_token_on_failure_path_also_raises
test_failed_start_log_is_recreated_before_the_completed_patch = scenarios.test_failed_start_log_is_recreated_before_the_completed_patch
test_failed_start_log_is_recreated_before_the_failed_patch = scenarios.test_failed_start_log_is_recreated_before_the_failed_patch
test_successful_start_log_is_not_re_posted = scenarios.test_successful_start_log_is_not_re_posted
test_persistent_execution_log_outage_is_reported_at_error = scenarios.test_persistent_execution_log_outage_is_reported_at_error
