"""Progress payload and failure-attribution contracts for execution orchestration."""

from tests.review.tasks import _execution_contract_scenarios as scenarios


test_success_emits_one_deleted_progress_post = scenarios.test_success_emits_one_deleted_progress_post
test_failure_emits_failed_progress_post_with_failed_at_step = scenarios.test_failure_emits_failed_progress_post_with_failed_at_step
test_sha256_mismatch_maps_to_failed_at_verify = scenarios.test_sha256_mismatch_maps_to_failed_at_verify
test_delete_failure_maps_to_failed_at_delete = scenarios.test_delete_failure_maps_to_failed_at_delete
test_sub_batch_terminal_set_on_last_item_only = scenarios.test_sub_batch_terminal_set_on_last_item_only
test_progress_post_failure_logs_warning_but_does_not_raise = scenarios.test_progress_post_failure_logs_warning_but_does_not_raise
test_error_message_uses_step_reason_prefix = scenarios.test_error_message_uses_step_reason_prefix
