"""Crash, replay, and collision-recovery contracts for execution."""

from tests.review.tasks import _execution_contract_scenarios as scenarios


test_crash_retry_already_moved_reports_completed_not_stale_failed = scenarios.test_crash_retry_already_moved_reports_completed_not_stale_failed
test_crash_retry_already_moved_with_hash_verifies_against_proposed = scenarios.test_crash_retry_already_moved_with_hash_verifies_against_proposed
test_crash_retry_hash_mismatch_at_proposed_is_still_a_genuine_failure = (
    scenarios.test_crash_retry_hash_mismatch_at_proposed_is_still_a_genuine_failure
)
test_crash_retry_already_moved_uncorroborated_fails_loudly_not_silently = (
    scenarios.test_crash_retry_already_moved_uncorroborated_fails_loudly_not_silently
)
test_duplicate_missing_source_is_not_silently_executed_onto_another_records_path = (
    scenarios.test_duplicate_missing_source_is_not_silently_executed_onto_another_records_path
)
test_cross_fs_replay_committed_copy_completes_move_not_clobber_fail = scenarios.test_cross_fs_replay_committed_copy_completes_move_not_clobber_fail
test_cross_fs_replay_committed_copy_with_hash_completes_move = scenarios.test_cross_fs_replay_committed_copy_with_hash_completes_move
test_already_moved_replay_cleans_up_orphaned_commit_marker = scenarios.test_already_moved_replay_cleans_up_orphaned_commit_marker
test_already_moved_replay_via_moved_flag_cleans_up_absent_marker_safely = (
    scenarios.test_already_moved_replay_via_moved_flag_cleans_up_absent_marker_safely
)
test_cross_fs_foreign_file_at_destination_still_refused = scenarios.test_cross_fs_foreign_file_at_destination_still_refused
test_cross_fs_duplicates_own_already_completed_move_is_refused_not_deleted = (
    scenarios.test_cross_fs_duplicates_own_already_completed_move_is_refused_not_deleted
)
test_cross_fs_unlink_failure_leaves_complete_copy_and_retry_does_not_recopy = (
    scenarios.test_cross_fs_unlink_failure_leaves_complete_copy_and_retry_does_not_recopy
)
