"""Pydantic schemas for POST /api/internal/agent/exec-batches/{batch_id}/progress (Phase 28 D-06).

Per D-06: per-proposal terminal-state progress event posted by the agent's
``execute_approved_batch`` task at the end of every proposal lifecycle (one
POST per file). The schema enforces:

- ``extra="forbid"`` -- strict wire-format parsing (no spoofed fields can ride
  in alongside ``agent_id``; the cross-tenant guard in the router compares
  ``body.agent_id`` against the auth dep's ``agent.id`` so a forged
  ``agent_id`` field is caught at runtime, but ``extra="forbid"`` keeps the
  payload surface minimal at parse time).
- Cross-field invariant via ``model_validator(mode="after")``:
  ``failed_at_step`` is REQUIRED iff ``terminal_step == "failed"`` and MUST
  be ``None`` otherwise. This pairs with the D-07 counter-math rules: the
  controller's ``_compute_increments`` reads ``failed_at_step`` only on the
  ``failed`` branch, so a leaked non-null value on a successful terminal
  step would be a silent bug -- we reject it at the validator instead.
- ``agent_id: str`` (NOT ``uuid.UUID``) -- matches the kebab-case slug
  convention from Phase 24 D-01 (Agent.id) and Phase 26 D-18 (per-agent SAQ
  queue name ``phaze-agent-<agent_id>``).
- ``request_id: uuid.UUID`` -- Stripe-style idempotency key generated by the
  agent BEFORE the per-file lifecycle starts and persisted in SAQ job state
  so retries reuse the same UUID per proposal (D-15).
- ``sub_batch_terminal: bool = False`` -- the agent flips this to ``True`` on
  the LAST proposal of its sub-batch so the controller can detect when
  ``subjobs_completed`` reaches ``subjobs_expected`` and promote the batch
  status to ``complete`` / ``complete_with_errors`` (D-07 final clause).
"""

from typing import Literal
import uuid

from pydantic import BaseModel, ConfigDict, model_validator


class ExecBatchProgressPayload(BaseModel):
    """Per-proposal terminal-state progress event (Phase 28 D-06).

    The cross-field invariant on ``failed_at_step``/``terminal_step`` is the
    schema's single non-trivial rule -- everything else is straightforward
    Literal-narrowing + ``extra="forbid"``. The validator is ``mode="after"``
    so it sees the fully-populated instance (defaults applied) and can return
    a ``ValueError`` whose message points at the field name -- the
    422-from-FastAPI surface preserves the field name for the agent's error
    log without leaking handler internals.

    Threat model (T-28-02-V, ASVS V13):
    - ``extra="forbid"`` blocks every flavour of "ride-along field" attack.
    - The Literal narrowing on ``terminal_step``/``failed_at_step`` makes
      out-of-range values 422 at parse time -- before the handler sees them.
    - The cross-field validator closes the gap where Literal alone would
      accept a structurally-valid-but-semantically-broken pairing like
      ``terminal_step="copied"`` + ``failed_at_step="verify"``.
    """

    model_config = ConfigDict(extra="forbid")

    request_id: uuid.UUID
    batch_id: uuid.UUID
    agent_id: str
    sub_batch_index: int
    proposal_id: uuid.UUID
    terminal_step: Literal["copied", "verified", "deleted", "failed"]
    failed_at_step: Literal["copy", "verify", "delete"] | None = None
    sub_batch_terminal: bool = False

    @model_validator(mode="after")
    def _check_failed_at_step_coupling(self) -> "ExecBatchProgressPayload":
        """D-06 invariant: failed_at_step is required iff terminal_step == 'failed'."""
        if self.terminal_step == "failed" and self.failed_at_step is None:
            msg = "failed_at_step is required when terminal_step='failed'"
            raise ValueError(msg)
        if self.terminal_step != "failed" and self.failed_at_step is not None:
            msg = "failed_at_step must be null when terminal_step != 'failed'"
            raise ValueError(msg)
        return self
