"""Tests for CUE sheet generation service."""

from __future__ import annotations

import concurrent.futures
from pathlib import Path

from cueparser import CueSheet
import pytest

from phaze.services.cue_generator import (
    CueTrackData,
    generate_cue_content,
    next_cue_path,
    next_cue_path_and_version,
    parse_timestamp_string,
    retarget_cue_file_line,
    seconds_to_cue_timestamp,
    write_cue_file,
)


class TestSecondsToTimestamp:
    """Test CUE timestamp conversion at 75fps."""

    def test_zero(self):
        assert seconds_to_cue_timestamp(0.0) == "00:00:00"

    def test_half_second(self):
        # 0.5s * 75 = 37.5, int = 37 frames
        assert seconds_to_cue_timestamp(0.5) == "00:00:37"

    def test_five_and_half_seconds(self):
        # 5.5 * 75 = 412.5 -> 412 frames
        # 412 % 75 = 37 frames, 412 // 75 = 5 secs
        # 5 // 60 = 0 min, 5 % 60 = 5 sec
        assert seconds_to_cue_timestamp(5.5) == "00:05:37"

    def test_mixed_minutes_seconds(self):
        # 332.45 * 75 = 24933.75 -> 24933 total frames
        # 24933 % 75 = 33 frames
        # 24933 // 75 = 332 secs -> 5 min 32 sec
        assert seconds_to_cue_timestamp(332.45) == "05:32:33"

    def test_over_60_minutes(self):
        # 3661.0 * 75 = 274575 frames
        # 274575 % 75 = 0 frames
        # 274575 // 75 = 3661 secs -> 61 min 1 sec
        assert seconds_to_cue_timestamp(3661.0) == "61:01:00"

    def test_frames_never_reach_75(self):
        # Test edge: 0.99333... seconds -> 74.5 frames -> 74
        result = seconds_to_cue_timestamp(0.99333333)
        frames = int(result.split(":")[2])
        assert frames < 75

    def test_exact_one_minute(self):
        assert seconds_to_cue_timestamp(60.0) == "01:00:00"

    def test_exact_one_second(self):
        assert seconds_to_cue_timestamp(1.0) == "00:01:00"

    def test_max_frame_value(self):
        # 74/75 of a second = 0.98666... -> 74 frames exactly
        result = seconds_to_cue_timestamp(74 / 75)
        assert result == "00:00:74"


class TestParseTimestampString:
    """Test timestamp string parsing."""

    def test_none_returns_none(self):
        assert parse_timestamp_string(None) is None

    def test_hh_mm_ss(self):
        assert parse_timestamp_string("1:30:00") == 5400.0

    def test_mm_ss(self):
        assert parse_timestamp_string("5:32") == 332.0

    def test_raw_seconds_float(self):
        assert parse_timestamp_string("332.45") == 332.45

    def test_raw_seconds_integer(self):
        assert parse_timestamp_string("60") == 60.0

    def test_zero(self):
        assert parse_timestamp_string("0:00") == 0.0

    def test_long_set_hh_mm_ss(self):
        # 2:15:30 = 2*3600 + 15*60 + 30 = 8130
        assert parse_timestamp_string("2:15:30") == 8130.0

    def test_empty_string_returns_none(self):
        # phaze-97u7: an empty scraped cue-time cell yields "" (not None) -- float("") must not raise.
        assert parse_timestamp_string("") is None

    def test_whitespace_returns_none(self):
        assert parse_timestamp_string("   ") is None

    def test_non_numeric_returns_none(self):
        assert parse_timestamp_string("abc") is None

    def test_decorated_time_returns_none(self):
        assert parse_timestamp_string("~5:00") is None

    def test_bracketed_time_returns_none(self):
        assert parse_timestamp_string("[1:02:03]") is None

    def test_trailing_garbage_returns_none(self):
        assert parse_timestamp_string("05:24*") is None

    def test_too_many_segments_returns_none(self):
        assert parse_timestamp_string("1:2:3:4") is None

    def test_fractional_seconds_segment_returns_none(self):
        # int(part) rejects a fractional MM/SS segment -- documented as None, not a crash.
        assert parse_timestamp_string("1:23:45.5") is None

    def test_garbage_minutes_segment_returns_none(self):
        assert parse_timestamp_string("12:xx") is None


class TestGenerateCueContent:
    """Test CUE content string generation."""

    def test_basic_generation(self):
        tracks = [
            CueTrackData(position=1, title="First Track", artist="Artist A", timestamp_seconds=0.0),
            CueTrackData(position=2, title="Second Track", artist="Artist B", timestamp_seconds=332.45),
        ]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        lines = content.strip().split("\n")

        assert lines[0] == 'REM COMMENT "Generated by Phaze"'
        assert lines[1] == 'FILE "test.mp3" MP3'
        assert lines[2] == "  TRACK 01 AUDIO"
        assert '    TITLE "First Track"' in content
        assert '    PERFORMER "Artist A"' in content
        assert "    INDEX 01 00:00:00" in content
        assert "  TRACK 02 AUDIO" in content
        assert '    TITLE "Second Track"' in content
        assert "    INDEX 01 05:32:33" in content

    def test_tracks_ordered_by_position(self):
        tracks = [
            CueTrackData(position=3, title="Third", artist=None, timestamp_seconds=200.0),
            CueTrackData(position=1, title="First", artist=None, timestamp_seconds=0.0),
            CueTrackData(position=2, title="Second", artist=None, timestamp_seconds=100.0),
        ]
        content = generate_cue_content("audio.wav", "wav", tracks)
        lines = content.strip().split("\n")

        # Find TRACK lines and verify order
        track_lines = [line for line in lines if "TRACK" in line and "AUDIO" in line]
        assert len(track_lines) == 3
        assert "TRACK 01" in track_lines[0]
        assert "TRACK 02" in track_lines[1]
        assert "TRACK 03" in track_lines[2]

    def test_tracks_without_timestamp_omitted(self):
        tracks = [
            CueTrackData(position=1, title="Has Time", artist=None, timestamp_seconds=0.0),
            CueTrackData(position=2, title="No Time", artist=None, timestamp_seconds=None),
            CueTrackData(position=3, title="Has Time Too", artist=None, timestamp_seconds=60.0),
        ]
        content = generate_cue_content("audio.mp3", "mp3", tracks)
        assert "No Time" not in content
        assert "TRACK 01" in content
        assert "TRACK 02" in content
        # Track numbering is sequential after filtering, not based on position
        assert "TRACK 03" not in content

    def test_file_type_mp3(self):
        content = generate_cue_content("test.mp3", "mp3", [])
        assert 'FILE "test.mp3" MP3' in content

    def test_file_type_wav(self):
        content = generate_cue_content("test.wav", "wav", [])
        assert 'FILE "test.wav" WAVE' in content

    def test_file_type_aiff(self):
        content = generate_cue_content("test.aiff", "aiff", [])
        assert 'FILE "test.aiff" AIFF' in content

    def test_file_type_flac(self):
        content = generate_cue_content("test.flac", "flac", [])
        assert 'FILE "test.flac" WAVE' in content

    def test_file_type_ogg(self):
        content = generate_cue_content("test.ogg", "ogg", [])
        assert 'FILE "test.ogg" WAVE' in content

    def test_file_type_m4a(self):
        content = generate_cue_content("test.m4a", "m4a", [])
        assert 'FILE "test.m4a" WAVE' in content

    def test_file_type_opus(self):
        content = generate_cue_content("test.opus", "opus", [])
        assert 'FILE "test.opus" WAVE' in content

    def test_file_type_unknown_defaults_wave(self):
        content = generate_cue_content("test.xyz", "xyz", [])
        assert 'FILE "test.xyz" WAVE' in content

    def test_double_quotes_stripped_from_filename(self):
        content = generate_cue_content('file"with"quotes.mp3', "mp3", [])
        assert 'FILE "filewithquotes.mp3" MP3' in content

    def test_double_quotes_stripped_from_title(self):
        # phaze-oo35: an embedded quote in TITLE must not terminate the field early.
        tracks = [CueTrackData(position=1, title='ID "Unreleased" Mix', artist=None, timestamp_seconds=0.0)]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        assert 'TITLE "ID Unreleased Mix"' in content
        assert '"ID "Unreleased" Mix"' not in content

    def test_double_quotes_stripped_from_performer(self):
        tracks = [CueTrackData(position=1, title="Track", artist='DJ "Loud" Name', timestamp_seconds=0.0)]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        assert 'PERFORMER "DJ Loud Name"' in content
        assert '"DJ "Loud" Name"' not in content

    def test_double_quotes_stripped_from_rem_label(self):
        tracks = [CueTrackData(position=1, title="Track", artist=None, timestamp_seconds=0.0, label='Some "Imprint" Records')]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        assert 'REM LABEL "Some Imprint Records"' in content
        assert '"Some "Imprint" Records"' not in content

    def test_double_quotes_stripped_from_rem_genre(self):
        tracks = [CueTrackData(position=1, title="Track", artist=None, timestamp_seconds=0.0, genre='"Deep" House')]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        assert 'REM GENRE "Deep House"' in content
        assert '""Deep" House"' not in content

    def test_newline_in_title_cannot_inject_file_directive(self):
        # phaze-4ea3: CUE is line-oriented -- an embedded newline must not terminate the TITLE
        # field early and let the remainder of the payload start a new top-level CUE directive
        # (e.g. a second FILE line that redirects playback to a different audio file). The
        # injected payload text is still visible (sanitization is not redaction), but it must
        # collapse onto the TITLE line rather than emit a real second FILE directive.
        payload = 'ID\nFILE "../other-artist-set.mp3" MP3\n  TRACK 02 AUDIO\n    TITLE "x'
        tracks = [CueTrackData(position=1, title=payload, artist=None, timestamp_seconds=0.0)]
        content = generate_cue_content("real-audio.mp3", "mp3", tracks)

        assert content.count('FILE "') == 1
        assert 'FILE "real-audio.mp3" MP3' in content
        # The line count must match a clean single-FILE, single-TRACK cue: REM COMMENT, FILE,
        # TRACK, TITLE, INDEX. A successful injection would add extra lines from the payload.
        assert content.count("\n") == 5
        # No line in the output may itself start a bare FILE/TRACK directive originating from
        # the payload -- everything from the payload must live inside the TITLE field's quotes.
        title_line = next(line for line in content.splitlines() if line.strip().startswith("TITLE"))
        assert "other-artist-set.mp3" in title_line

    def test_carriage_return_in_title_cannot_inject_directive(self):
        payload = 'x"\rFILE "other.mp3" MP3'
        tracks = [CueTrackData(position=1, title=payload, artist=None, timestamp_seconds=0.0)]
        content = generate_cue_content("real-audio.mp3", "mp3", tracks)

        assert content.count('FILE "') == 1
        assert content.count("\n") == 5

    def test_newline_in_performer_cannot_inject_directive(self):
        payload = 'DJ\nFILE "other.mp3" MP3'
        tracks = [CueTrackData(position=1, title="Track", artist=payload, timestamp_seconds=0.0)]
        content = generate_cue_content("real-audio.mp3", "mp3", tracks)

        assert content.count('FILE "') == 1
        assert content.count("\n") == 6

    def test_newline_in_rem_label_cannot_inject_directive(self):
        payload = 'Imprint\nFILE "other.mp3" MP3'
        tracks = [CueTrackData(position=1, title="Track", artist=None, timestamp_seconds=0.0, label=payload)]
        content = generate_cue_content("real-audio.mp3", "mp3", tracks)

        assert content.count('FILE "') == 1
        assert content.count("\n") == 6

    def test_newline_in_rem_genre_cannot_inject_directive(self):
        payload = 'House\nFILE "other.mp3" MP3'
        tracks = [CueTrackData(position=1, title="Track", artist=None, timestamp_seconds=0.0, genre=payload)]
        content = generate_cue_content("real-audio.mp3", "mp3", tracks)

        assert content.count('FILE "') == 1
        assert content.count("\n") == 6

    def test_newline_in_filename_cannot_inject_directive(self):
        content = generate_cue_content('real-audio.mp3\nFILE "other.mp3" MP3', "mp3", [])

        assert content.count('FILE "') == 1
        assert content.count("\n") == 2

    def test_trailing_newline(self):
        content = generate_cue_content("test.mp3", "mp3", [])
        assert content.endswith("\n")

    def test_no_artist_or_title(self):
        tracks = [
            CueTrackData(position=1, title=None, artist=None, timestamp_seconds=0.0),
        ]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        assert "TITLE" not in content
        assert "PERFORMER" not in content
        assert "INDEX 01 00:00:00" in content

    def test_case_insensitive_file_type(self):
        content = generate_cue_content("test.mp3", "MP3", [])
        assert 'FILE "test.mp3" MP3' in content


class TestDiscogRem:
    """Test Discogs REM comment generation."""

    def test_full_discogs_metadata(self):
        tracks = [
            CueTrackData(
                position=1,
                title="Track One",
                artist="Artist",
                timestamp_seconds=0.0,
                genre="House",
                label="Defected Records",
                year=2023,
            ),
        ]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        assert '    REM GENRE "House"' in content
        assert '    REM LABEL "Defected Records"' in content
        assert '    REM YEAR "2023"' in content

    def test_no_discogs_metadata(self):
        tracks = [
            CueTrackData(position=1, title="Track", artist="Artist", timestamp_seconds=0.0),
        ]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        assert "REM GENRE" not in content
        assert "REM LABEL" not in content
        assert "REM YEAR" not in content

    def test_partial_discogs_metadata(self):
        tracks = [
            CueTrackData(
                position=1,
                title="Track",
                artist="Artist",
                timestamp_seconds=0.0,
                genre="Techno",
                label=None,
                year=None,
            ),
        ]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        assert '    REM GENRE "Techno"' in content
        assert "REM LABEL" not in content
        assert "REM YEAR" not in content

    def test_rem_order_before_title(self):
        tracks = [
            CueTrackData(
                position=1,
                title="Track",
                artist="Artist",
                timestamp_seconds=0.0,
                genre="House",
                label="Label",
                year=2023,
            ),
        ]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        lines = content.strip().split("\n")
        # Find REM and TITLE line indices
        rem_genre_idx = next(i for i, line in enumerate(lines) if "REM GENRE" in line)
        title_idx = next(i for i, line in enumerate(lines) if "TITLE" in line)
        assert rem_genre_idx < title_idx

    def test_mixed_tracks_with_and_without_discogs(self):
        tracks = [
            CueTrackData(
                position=1,
                title="Linked",
                artist="A",
                timestamp_seconds=0.0,
                genre="House",
                label="Label",
                year=2023,
            ),
            CueTrackData(
                position=2,
                title="Unlinked",
                artist="B",
                timestamp_seconds=60.0,
            ),
        ]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        lines = content.strip().split("\n")
        # Track 1 should have REM lines, Track 2 should not
        track2_start = next(i for i, line in enumerate(lines) if "TRACK 02" in line)
        track2_lines = lines[track2_start:]
        track2_block = "\n".join(track2_lines)
        assert "REM GENRE" not in track2_block


class TestNextCuePath:
    """Test version suffix naming for CUE files."""

    def test_first_cue_no_existing(self, tmp_path):
        audio = tmp_path / "audio.mp3"
        audio.touch()
        result = next_cue_path(audio)
        assert result == tmp_path / "audio.cue"

    def test_second_cue_when_base_exists(self, tmp_path):
        audio = tmp_path / "audio.mp3"
        audio.touch()
        (tmp_path / "audio.cue").touch()
        result = next_cue_path(audio)
        assert result == tmp_path / "audio.v2.cue"

    def test_third_cue_when_base_and_v2_exist(self, tmp_path):
        audio = tmp_path / "audio.mp3"
        audio.touch()
        (tmp_path / "audio.cue").touch()
        (tmp_path / "audio.v2.cue").touch()
        result = next_cue_path(audio)
        assert result == tmp_path / "audio.v3.cue"

    def test_gap_in_versions(self, tmp_path):
        audio = tmp_path / "audio.mp3"
        audio.touch()
        (tmp_path / "audio.cue").touch()
        (tmp_path / "audio.v3.cue").touch()
        # v2 missing, but max is 3 -> next is v4
        result = next_cue_path(audio)
        assert result == tmp_path / "audio.v4.cue"


class TestWriteCueFile:
    """Test CUE file writing with UTF-8 BOM.

    phaze-9dwb: ``write_cue_file`` now returns ``(path, version)``. The version is computed by the
    directory scan the write already performs, so the caller no longer re-walks the archive
    directory a second time purely to recover a number it just threw away.
    """

    def test_written_file_has_bom(self, tmp_path):
        audio = tmp_path / "<track-01>.mp3"
        audio.touch()
        content = 'REM COMMENT "Generated by Phaze"\nFILE "<track-01>.mp3" MP3\n'
        result, _version = write_cue_file(content, audio)
        raw = result.read_bytes()
        assert raw[:3] == b"\xef\xbb\xbf"

    def test_content_matches(self, tmp_path):
        audio = tmp_path / "<track-01>.mp3"
        audio.touch()
        content = 'REM COMMENT "Generated by Phaze"\nFILE "<track-01>.mp3" MP3\n'
        result, _version = write_cue_file(content, audio)
        # Read back, stripping BOM
        text = result.read_text(encoding="utf-8-sig")
        assert text == content

    def test_returns_path(self, tmp_path):
        audio = tmp_path / "<track-01>.mp3"
        audio.touch()
        result, _version = write_cue_file("content\n", audio)
        assert isinstance(result, Path)
        assert result.exists()

    def test_version_increment_on_rewrite(self, tmp_path):
        audio = tmp_path / "<track-01>.mp3"
        audio.touch()
        first, first_version = write_cue_file("v1\n", audio)
        assert first.name == "<track-01>.cue"
        second, second_version = write_cue_file("v2\n", audio)
        assert second.name == "<track-01>.v2.cue"
        # phaze-9dwb: the version travels back WITH the path, so the caller needs no second scan.
        assert (first_version, second_version) == (1, 2)

    def test_version_matches_a_fresh_scan(self, tmp_path):
        """The returned version equals what an independent scan of the directory would report.

        Guards the whole point of returning it: the number must be the same one the deleted
        ``routers/cue.py::_get_cue_version`` re-derived, not an off-by-one reinterpretation.
        """
        audio = tmp_path / "<set-01>.mp3"
        audio.touch()
        write_cue_file("v1\n", audio)
        write_cue_file("v2\n", audio)
        next_path, next_version = next_cue_path_and_version(audio)
        assert next_path.name == "<set-01>.v3.cue"
        assert next_version == 3


class TestWriteCueFileConcurrency:
    """phaze-d16ax: ``next_cue_path_and_version`` PREDICTS a free path; the exclusive-create write
    must CLAIM one -- two concurrent writers racing the same predicted version must never let the
    second silently truncate the first.
    """

    def test_concurrent_writers_do_not_clobber_each_other(self, tmp_path):
        """Two genuinely concurrent writes for the SAME audio file must both survive on disk.

        Before the fix, both threads could scan before either created the file, both resolve the
        identical ``(path, version)``, and the truncating ``open("w")`` would let the second
        writer silently overwrite the first -- one operator-approved cue sheet lost with no error.
        The exclusive-create retry makes that structurally impossible: a losing writer gets
        ``FileExistsError``, re-scans, and claims the NEXT version instead.
        """
        audio = tmp_path / "<set-01>.mp3"
        audio.touch()

        with concurrent.futures.ThreadPoolExecutor(max_workers=2) as pool:
            future_a = pool.submit(write_cue_file, "content-a\n", audio)
            future_b = pool.submit(write_cue_file, "content-b\n", audio)
            (path_a, version_a) = future_a.result()
            (path_b, version_b) = future_b.result()

        # Both writers must have claimed DISTINCT paths/versions -- neither lost its content.
        assert path_a != path_b
        assert {version_a, version_b} == {1, 2}
        assert path_a.read_text(encoding="utf-8-sig") == "content-a\n"
        assert path_b.read_text(encoding="utf-8-sig") == "content-b\n"

    def test_retries_past_a_losing_race_then_succeeds(self, tmp_path, monkeypatch):
        """A single lost race (one ``FileExistsError``) is retried transparently, not surfaced."""
        import phaze.services.cue_generator as cue_generator_module

        audio = tmp_path / "<set-01>.mp3"
        audio.touch()

        real_os_open = cue_generator_module.os.open
        calls = {"n": 0}

        def flaky_open(path, flags, mode=0o777):
            calls["n"] += 1
            if calls["n"] == 1:
                raise FileExistsError(f"simulated race on {path}")
            return real_os_open(path, flags, mode)

        monkeypatch.setattr(cue_generator_module.os, "open", flaky_open)

        path, version = write_cue_file("content\n", audio)
        assert calls["n"] == 2, "exactly one retry after the simulated race"
        assert version == 1
        assert path.read_text(encoding="utf-8-sig") == "content\n"

    def test_persistent_collision_raises_instead_of_spinning_forever(self, tmp_path, monkeypatch):
        """Every attempt losing the exclusive create must raise, not loop unboundedly."""
        import phaze.services.cue_generator as cue_generator_module

        audio = tmp_path / "<set-01>.mp3"
        audio.touch()

        def always_fails(path, flags, mode=0o777):
            raise FileExistsError(f"simulated persistent collision on {path}")

        monkeypatch.setattr(cue_generator_module.os, "open", always_fails)

        with pytest.raises(RuntimeError, match="Could not claim"):
            write_cue_file("content\n", audio)


class TestRetargetCueFileLine:
    """phaze-pqib3 (seam C5): the ``FILE`` name is a fact about where the sheet LANDS.

    ``routers/cue.py`` renders it from the unresolved ``current_path`` because that is the only
    name the api can know (no media mount, DIST-01); ``tasks/cue_write.py::_write_sync`` resolves
    that path and writes beside the target, so the two disagree for any symlink into a
    differently-named file. This is the reconciliation, and these are its edges.
    """

    def _sheet(self, name: str) -> str:
        return f'REM COMMENT "Generated by Phaze"\nFILE "{name}" MP3\n  TRACK 01 AUDIO\n    INDEX 01 00:00:00\n'

    def test_replaces_the_name_and_keeps_the_type_token(self):
        """Only the quoted name moves -- the trailing format token is what tells a parser how to decode."""
        out = retarget_cue_file_line(self._sheet("<set-01>.mp3"), "<set-02>.mp3")
        assert 'FILE "<set-02>.mp3" MP3' in out
        assert "<set-01>.mp3" not in out

    def test_an_already_correct_sheet_is_returned_byte_identical(self):
        """The overwhelming majority of the archive: ``current_path`` is its own realpath.

        The retarget must be a genuine no-op there, not a re-render that could drift from what the
        operator previewed.
        """
        sheet = self._sheet("<set-01>.mp3")
        assert retarget_cue_file_line(sheet, "<set-01>.mp3") == sheet

    def test_everything_after_the_file_directive_is_untouched(self):
        """A sheet is mostly TRACK/INDEX records; a name swap must not perturb one."""
        sheet = self._sheet("<set-01>.mp3")
        out = retarget_cue_file_line(sheet, "<set-02>.mp3")
        assert out.splitlines()[0] == sheet.splitlines()[0]
        assert out.splitlines()[2:] == sheet.splitlines()[2:]

    def test_the_new_name_is_sanitized_like_a_rendered_one(self):
        """phaze-4ea3, now on the AGENT's side of the wire.

        The replacement is a real filesystem basename, and a filename may legally contain a quote
        or (on some filesystems) a control character. Unsanitized, either terminates the field or
        the record early -- the same FILE-injection shape ``_cue_quote`` exists to close.
        """
        out = retarget_cue_file_line(self._sheet("<set-01>.mp3"), 'ev"il\nFILE "elsewhere.mp3')

        # One DIRECTIVE, not one occurrence of the word: the injected text is meant to survive as
        # inert characters INSIDE the quoted name, which is exactly what collapsing it onto the
        # same line achieves.
        assert [line for line in out.splitlines() if line.startswith("FILE ")] == ['FILE "evil FILE elsewhere.mp3" MP3']

    def test_a_backslash_escape_in_the_name_is_not_expanded(self):
        """``re.sub`` reads ``\\1`` in a TEMPLATE string as a backreference; the name is data, not a template."""
        out = retarget_cue_file_line(self._sheet("<set-01>.mp3"), r"\1\g<0>.mp3")
        assert r'FILE "\1\g<0>.mp3" MP3' in out

    def test_no_file_directive_raises_rather_than_writing_an_unanchored_sheet(self):
        """A sheet with no audio reference is useless to its consumer -- fail the job, do not write it.

        Unreachable from :func:`generate_cue_content`, which always emits exactly one. Guarded
        because the alternative is the lenient default CLAUDE.md names: silently writing an
        artifact that names nothing.
        """
        with pytest.raises(ValueError, match="0 FILE directives"):
            retarget_cue_file_line('REM COMMENT "Generated by Phaze"\n', "<set-01>.mp3")

    def test_two_file_directives_raise_rather_than_retargeting_one_of_them(self):
        """Two references means the sheet is ambiguous about its own audio; retargeting one hides that."""
        doubled = self._sheet("<set-01>.mp3") + 'FILE "<set-02>.mp3" MP3\n'
        with pytest.raises(ValueError, match="2 FILE directives"):
            retarget_cue_file_line(doubled, "<set-03>.mp3")


class TestRealCueConsumer:
    """Seam C2 (phaze-bp8h1): the ``.cue`` file :func:`write_cue_file` puts on disk had never been
    READ by anything but phaze's own substring/line-count assertions on the string
    :func:`generate_cue_content` returned. ``cueparser`` (PyPI ``CueParser``, MIT license,
    github.com/artur-shaik/CueParser, actively maintained) is a real, independent third-party
    implementation that shares no code and no assumptions with
    :mod:`phaze.services.cue_generator` -- these tests hand it the REAL bytes the real producer
    pipeline (:func:`generate_cue_content` then :func:`write_cue_file`) writes: UTF-8 BOM, bare
    ``\\n`` line endings, quote-stripped fields, 75fps ``INDEX``.

    CAVEAT, so this is not over-read: ``cueparser``'s own ``TITLE``/``PERFORMER`` regex is loose
    (it strips only the first and last character of the matched line -- it does not implement
    CUE's real quoting grammar). It therefore says nothing about phaze's choice to STRIP embedded
    quotes rather than escape them (see :func:`_cue_quote`'s docstring) -- only about whether the
    produced bytes are structurally readable by a real consumer at all: file name, track count,
    titles, performers and INDEX offsets. It also never observes CRLF vs LF, because it splits
    purely on ``\\n``. Neither foobar2000 nor a real ``cuetools`` binary was available in this
    environment to cross-check independently; a check of this machine's ffmpeg (9.0.2, Homebrew)
    found NO cue demuxer/format/protocol at all, so the "ffmpeg's cue demuxer is already a system
    dependency" alternative the bead named does not hold here either -- recorded on the bead.

    :class:`TestRealCueConsumerIsDiscriminating` below shows this consumer is not a rubber stamp
    (CLAUDE.md rule 3): it reports a truncated sheet's track count correctly, echoes a wrong
    ``INDEX`` value rather than "correcting" it, and desyncs on an unescaped newline in a quoted
    field.
    """

    def _parse(self, raw: str) -> CueSheet:
        sheet = CueSheet()
        sheet.setOutputFormat("", "")
        sheet.setData(raw)
        sheet.parse()
        return sheet

    def test_real_parser_reads_track_count_titles_performers_and_index_offsets(self, tmp_path):
        """The end-to-end producer path, read by a real external consumer -- not phaze reading its own output back."""
        tracks = [
            CueTrackData(
                position=1, title='Opening "Act" One', artist='DJ Quo"te', timestamp_seconds=0.0, genre="House", label="<label-01>", year=2024
            ),
            CueTrackData(position=2, title="Second Track", artist="Artist Two", timestamp_seconds=125.5),
            CueTrackData(position=3, title="Third Track", artist="Artist Three", timestamp_seconds=3661.24),
        ]
        content = generate_cue_content("<track-01>.mp3", "mp3", tracks)
        audio = tmp_path / "<track-01>.mp3"
        audio.touch()
        path, _version = write_cue_file(content, audio)

        # A spec-aware reader decodes utf-8-sig, exactly like the existing readback tests above.
        sheet = self._parse(path.read_text(encoding="utf-8-sig"))

        assert sheet.file == "<track-01>.mp3"
        assert len(sheet.tracks) == 3
        assert [t.title for t in sheet.tracks] == ["Opening Act One", "Second Track", "Third Track"]
        assert [t.performer for t in sheet.tracks] == ["DJ Quote", "Artist Two", "Artist Three"]
        assert [t.offset for t in sheet.tracks] == [
            seconds_to_cue_timestamp(0.0),
            seconds_to_cue_timestamp(125.5),
            seconds_to_cue_timestamp(3661.24),
        ]

    def test_real_parser_still_resolves_track_structure_without_bom_stripping(self, tmp_path):
        """FINDING, recorded per the AC, not escalated: this consumer does not reject the BOM.

        Decoded via plain ``utf-8`` -- the BOM survives as a literal U+FEFF, the same shape
        ``companion_read.read_companion_bounded_sync`` had before its own fix for READS
        (phaze-mi5y0, a sibling bead) -- this consumer's line-oriented recursive parser loses only
        the ``REM COMMENT`` header line (its ``^REM `` regex does not match a BOM-prefixed line)
        and resynchronizes on the very next line, so FILE/TRACK/INDEX parsing is unaffected. No
        format-decision escalation follows from this test: the artifact remains readable by this
        real consumer either way.
        """
        tracks = [CueTrackData(position=1, title="T1", artist="A1", timestamp_seconds=90.0)]
        content = generate_cue_content("<track-01>.mp3", "mp3", tracks)
        audio = tmp_path / "<track-01>.mp3"
        audio.touch()
        path, _version = write_cue_file(content, audio)

        raw_with_literal_bom = path.read_text(encoding="utf-8")
        assert raw_with_literal_bom[0] == "﻿"  # confirms the BOM really is still there, unstripped

        sheet = self._parse(raw_with_literal_bom)
        assert sheet.file == "<track-01>.mp3"
        assert len(sheet.tracks) == 1
        assert sheet.tracks[0].title == "T1"
        assert sheet.tracks[0].offset == seconds_to_cue_timestamp(90.0)


class TestRealCueConsumerIsDiscriminating:
    """CLAUDE.md rule 3: an independent consumer means something only once it is shown to REJECT
    or MIS-REPORT a deliberately wrong sheet -- accepting phaze's real output alone is not enough.
    """

    def _parse(self, raw: str) -> CueSheet:
        sheet = CueSheet()
        sheet.setOutputFormat("", "")
        sheet.setData(raw)
        sheet.parse()
        return sheet

    def test_a_truncated_sheet_reports_fewer_tracks_than_a_correct_one(self):
        truncated = 'REM COMMENT "Generated by Phaze"\nFILE "<track-01>.mp3" MP3\n  TRACK 01 AUDIO\n    TITLE "T1"\n    INDEX 01 00:00:00\n'
        sheet = self._parse(truncated)
        assert len(sheet.tracks) == 1  # a correct 2-track sheet would report 2 here

    def test_a_wrong_index_frame_value_is_echoed_verbatim_not_corrected(self):
        correct = seconds_to_cue_timestamp(90.49)
        wrong = 'REM COMMENT "Generated by Phaze"\nFILE "<track-01>.mp3" MP3\n  TRACK 01 AUDIO\n    TITLE "T1"\n    INDEX 01 01:30:00\n'
        sheet = self._parse(wrong)
        assert sheet.tracks[0].offset != correct
        assert sheet.tracks[0].offset == "01:30:00"

    def test_an_unescaped_newline_in_a_quoted_field_desyncs_the_parse(self):
        """The FILE-injection shape :func:`_cue_quote` exists to prevent (phaze-4ea3): a raw
        ``\\n`` surviving inside a quoted value lets it terminate the record early. Real
        production content never reaches this state -- ``_cue_quote`` strips every control
        character before a value is interpolated -- so this constructs the sheet BY HAND,
        bypassing the generator entirely, to show the real consumer is sensitive to exactly the
        corruption the generator's own sanitization prevents.
        """
        clean = 'REM COMMENT "Generated by Phaze"\nFILE "<track-01>.mp3" MP3\n  TRACK 01 AUDIO\n    TITLE "Evil"\n    INDEX 01 00:00:00\n'
        injected = 'REM COMMENT "Generated by Phaze"\nFILE "<track-01>.mp3" MP3\n  TRACK 01 AUDIO\n    TITLE "Evil\nFILE "hijack.mp3" WAVE"\n    INDEX 01 00:00:00\n'

        clean_sheet = self._parse(clean)
        injected_sheet = self._parse(injected)

        assert clean_sheet.tracks[0].title == "Evil"
        assert injected_sheet.tracks[0].title != clean_sheet.tracks[0].title or len(injected_sheet.tracks) != len(clean_sheet.tracks)
