#!/usr/bin/env bash
# Generate the synthetic audio corpus used by the phaze-han03 essentia-seek spike.
#
# Everything this spike measures is generated by THIS script from THIS command line.
# No operator media is involved at any point, which is what makes the numbers (and the
# prototype patch) publishable to a public upstream tracker.
#
# The signal is deliberately shaped to be useful for three different jobs at once:
#
#   * A 220 / 261.626 / 329.628 Hz triad (A3 / C4 / E4 -- A minor) with a 6/s exponential
#     decay retriggered every 0.5 s, plus a sharp 40/s transient on the same period.
#     0.5 s => 120 BPM, so BPM and key are both WELL DEFINED and can be compared between
#     a seeked read and a decode-and-discard read.
#   * A slow chirp (instantaneous frequency drifts with t) so the waveform is GLOBALLY
#     UNIQUE. Without it the signal is exactly periodic at 0.5 s and a sample-accuracy
#     test could not distinguish a correct seek from one that is wrong by a whole number
#     of bars.
#   * A pure deterministic function of t, so the same command reproduces the same samples
#     on any machine -- no seeded RNG, no encoder nondeterminism in the WAV reference.
#
# Usage: make-synthetic-corpus.sh <output-dir>
set -euo pipefail

OUT="${1:?usage: make-synthetic-corpus.sh <output-dir>}"
mkdir -p "$OUT"

# NOTE: inside an lavfi filtergraph, ':' separates options and ',' separates filters, so
# every ',' inside the expression must be backslash-escaped. The expression is otherwise
# ordinary ffmpeg eval syntax.
DECAY='exp(-6*mod(t\,0.5))'
EXPR="0.34*sin(2*PI*220*t)*${DECAY}+0.28*sin(2*PI*261.626*t)*${DECAY}+0.22*sin(2*PI*329.628*t)*${DECAY}+0.30*exp(-40*mod(t\,0.5))+0.15*sin(2*PI*(300+0.05*t)*t)"

gen_wav() { # gen_wav <seconds> <rate> <path>
  ffmpeg -hide_banner -loglevel error -y \
    -f lavfi -i "aevalsrc=exprs=${EXPR}:s=$2:d=$1" \
    -c:a pcm_s16le "$3"
}

# --- accuracy corpus: 600 s, one lossless reference + one file per container/codec ------
gen_wav 600 44100 "$OUT/synth-600s.wav"
ffmpeg -hide_banner -loglevel error -y -i "$OUT/synth-600s.wav" -c:a libmp3lame -b:a 192k "$OUT/synth-600s.mp3"
ffmpeg -hide_banner -loglevel error -y -i "$OUT/synth-600s.wav" -c:a aac -b:a 192k "$OUT/synth-600s.m4a"
# Opus rather than Vorbis: it is what this ffmpeg build ships, and it is the HARDER
# sample-accuracy case -- Opus carries a codec delay ("pre-skip") in the container and
# always decodes at 48 kHz regardless of the input rate, so it exercises both the
# packet-boundary and the rate-conversion halves of a seek.
ffmpeg -hide_banner -loglevel error -y -i "$OUT/synth-600s.wav" -c:a libopus -b:a 192k "$OUT/synth-600s.opus"
ffmpeg -hide_banner -loglevel error -y -i "$OUT/synth-600s.wav" -c:a flac "$OUT/synth-600s.flac"

# --- timing corpus: long mp3, the shape the phaze chunked pipeline actually decodes ------
# 48 kHz variant included because phaze-b2qs9 4d found source sample rate to be a
# first-order term in decode cost (the fine tier resamples 48k -> 44.1k).
for secs in 3600 7200; do
  gen_wav "$secs" 44100 "$OUT/synth-${secs}s.wav"
  ffmpeg -hide_banner -loglevel error -y -i "$OUT/synth-${secs}s.wav" -c:a libmp3lame -b:a 192k "$OUT/synth-${secs}s.mp3"
  rm -f "$OUT/synth-${secs}s.wav"
done
gen_wav 3600 48000 "$OUT/synth-3600s-48k.wav"
ffmpeg -hide_banner -loglevel error -y -i "$OUT/synth-3600s-48k.wav" -c:a libmp3lame -b:a 192k "$OUT/synth-3600s-48k.mp3"
rm -f "$OUT/synth-3600s-48k.wav"

ls -l "$OUT"
