"""CUE sheet generation service.

Generates CUE sheet content from tracklist data with Discogs metadata
enrichment via REM comments. Handles timestamp conversion to CUE's
MM:SS:FF format at 75 frames per second, file type mapping, version
suffix naming, and UTF-8 BOM file writing.
"""

from __future__ import annotations

from dataclasses import dataclass
import re
from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from pathlib import Path


@dataclass
class CueTrackData:
    """Data for a single track in a CUE sheet."""

    position: int
    title: str | None = None
    artist: str | None = None
    timestamp_seconds: float | None = None
    genre: str | None = None
    label: str | None = None
    year: int | None = None


_FILE_TYPE_MAP: dict[str, str] = {
    "mp3": "MP3",
    "wav": "WAVE",
    "wave": "WAVE",
    "aiff": "AIFF",
    "aif": "AIFF",
    "flac": "WAVE",
    "ogg": "WAVE",
    "m4a": "WAVE",
    "opus": "WAVE",
}


def seconds_to_cue_timestamp(total_seconds: float) -> str:
    """Convert seconds to CUE MM:SS:FF format at 75 frames per second.

    Args:
        total_seconds: Time in seconds (float).

    Returns:
        String in MM:SS:FF format where FF is 00-74.
    """
    total_frames = int(total_seconds * 75)
    frames = total_frames % 75
    total_secs = total_frames // 75
    minutes = total_secs // 60
    seconds = total_secs % 60
    return f"{minutes:02d}:{seconds:02d}:{frames:02d}"


def parse_timestamp_string(ts: str | None) -> float | None:
    """Parse a timestamp string to total seconds.

    Supports formats:
        - "HH:MM:SS" -> hours*3600 + minutes*60 + seconds
        - "MM:SS" -> minutes*60 + seconds
        - "123.45" -> raw seconds as float

    Args:
        ts: Timestamp string or None.

    Returns:
        Total seconds as float, or None if input is None.
    """
    if ts is None:
        return None

    parts = ts.split(":")
    if len(parts) == 3:
        return float(int(parts[0]) * 3600 + int(parts[1]) * 60 + int(parts[2]))
    if len(parts) == 2:
        return float(int(parts[0]) * 60 + int(parts[1]))
    return float(ts)


def generate_cue_content(audio_filename: str, file_type: str, tracks: list[CueTrackData]) -> str:
    """Generate CUE sheet content as a string.

    Args:
        audio_filename: Name of the audio file (not full path).
        file_type: Audio file extension (e.g. "mp3", "wav").
        tracks: List of track data. Tracks without timestamp_seconds are omitted.

    Returns:
        Complete CUE sheet content string with trailing newline.
    """
    # Strip double quotes from filename (Pitfall 4)
    safe_filename = audio_filename.replace('"', "")

    cue_type = _FILE_TYPE_MAP.get(file_type.lower(), "WAVE")

    lines: list[str] = [
        'REM COMMENT "Generated by Phaze"',
        f'FILE "{safe_filename}" {cue_type}',
    ]

    # Filter out tracks without timestamps and sort by position
    valid_tracks = sorted(
        [t for t in tracks if t.timestamp_seconds is not None],
        key=lambda t: t.position,
    )

    for i, track in enumerate(valid_tracks, start=1):
        lines.append(f"  TRACK {i:02d} AUDIO")

        # REM comments from Discogs metadata (D-08, D-09)
        if track.genre:
            lines.append(f'    REM GENRE "{track.genre}"')
        if track.label:
            lines.append(f'    REM LABEL "{track.label}"')
        if track.year:
            lines.append(f'    REM YEAR "{track.year}"')

        # Track metadata
        if track.title:
            lines.append(f'    TITLE "{track.title}"')
        if track.artist:
            lines.append(f'    PERFORMER "{track.artist}"')

        # INDEX command with converted timestamp (timestamp_seconds guaranteed non-None by filter above)
        if track.timestamp_seconds is None:  # pragma: no cover — defensive guard; valid_tracks filters None above
            continue
        lines.append(f"    INDEX 01 {seconds_to_cue_timestamp(track.timestamp_seconds)}")

    return "\n".join(lines) + "\n"


def next_cue_path(audio_path: Path) -> Path:
    """Determine the next CUE file path with version suffix if needed.

    First CUE: "audio.cue"
    Second: "audio.v2.cue"
    Third: "audio.v3.cue"

    Args:
        audio_path: Path to the audio file.

    Returns:
        Path for the next CUE file.
    """
    base = audio_path.stem
    parent = audio_path.parent
    base_cue = parent / f"{base}.cue"

    if not base_cue.exists():
        return base_cue

    # Scan for existing versioned CUE files
    pattern = re.compile(rf"^{re.escape(base)}\.v(\d+)\.cue$")
    max_version = 1  # base_cue counts as v1

    for f in parent.iterdir():
        m = pattern.match(f.name)
        if m:
            max_version = max(max_version, int(m.group(1)))

    return parent / f"{base}.v{max_version + 1}.cue"


def write_cue_file(content: str, audio_path: Path) -> Path:
    """Write CUE content to filesystem with UTF-8 BOM encoding.

    Uses version suffix naming if a CUE file already exists.

    Args:
        content: CUE sheet content string.
        audio_path: Path to the audio file (used to determine CUE path).

    Returns:
        Path of the written CUE file.
    """
    path = next_cue_path(audio_path)
    with path.open("w", encoding="utf-8-sig") as f:
        f.write(content)
    return path
