"""Real-TLS integration tests for PhazeAgentClient verify= wiring (Phase 29 D-04).

Stands up a real uvicorn server with a leaf cert generated by
``phaze.cert_bootstrap.ensure_certs_present`` and exercises
``PhazeAgentClient(verify=<CA path>)`` -- the shape ``construct_agent_client``
uses in production -- against TWO independent CA bundles:

    1. wrong-CA  -> ``httpx.ConnectError`` (D-04 success criterion)
    2. correct-CA -> 200 OK response
    3. ``construct_agent_client(cfg)`` with a missing CA file
       -> ``RuntimeError("CA file empty or unreadable: ...")``

These tests intentionally do NOT use respx -- respx mocks at the httpx
transport layer below TLS, so it cannot exercise cert verification.
The trade-off is a slower test (real uvicorn boot + asyncio task) but
it is the only way to assert the rejection path that AUTH-02 promises.

The test is marked with ``pytest.mark.integration`` per
``[tool.pytest.ini_options] markers`` in pyproject.toml.
"""

from __future__ import annotations

import asyncio
import logging
import socket
import ssl
from typing import TYPE_CHECKING

from fastapi import FastAPI
import httpx
from pydantic import SecretStr
import pytest
import uvicorn

from phaze.cert_bootstrap import ensure_certs_present
from phaze.config import AgentSettings
from phaze.services.agent_client import PhazeAgentClient, _resolve_verify
from phaze.tasks._shared.agent_bootstrap import construct_agent_client


if TYPE_CHECKING:
    from collections.abc import AsyncIterator
    from pathlib import Path


pytestmark = pytest.mark.integration

# Bearer value for the two real-TLS clients below. Never sent anywhere -- the assertions are
# about certificate verification, and the stub endpoint does not read Authorization at all.
_TEST_TOKEN = "phaze_agent_test-token"


def _free_port() -> int:
    """Bind to port 0 to find an unused TCP port; release immediately."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return int(s.getsockname()[1])


async def _wait_for_tcp(host: str, port: int, timeout: float = 5.0) -> None:
    """Poll until a TCP connect to (host, port) succeeds or timeout elapses."""
    deadline = asyncio.get_running_loop().time() + timeout
    while asyncio.get_running_loop().time() < deadline:
        try:
            reader, writer = await asyncio.open_connection(host, port)
            writer.close()
            await writer.wait_closed()
        except (OSError, ConnectionRefusedError):
            await asyncio.sleep(0.05)
        else:
            del reader
            return
    msg = f"server did not start listening on {host}:{port} within {timeout}s"
    raise TimeoutError(msg)


@pytest.fixture
async def tls_server(tmp_path: Path) -> AsyncIterator[tuple[int, Path, Path]]:
    """Spin up a uvicorn server with a real TLS cert in tmp_path/server_certs.

    Yields ``(port, server_certs_dir, wrong_certs_dir)``:
        - ``port``: the bound port the server listens on
        - ``server_certs_dir``: dir holding ``phaze-ca.crt`` matching the
          server's leaf (the "correct" CA from the agent's POV)
        - ``wrong_certs_dir``: dir holding a DIFFERENT CA -- the agent's
          verify= path uses this to prove untrusted certs are rejected
    """
    server_certs_dir = tmp_path / "server_certs"
    wrong_certs_dir = tmp_path / "wrong_certs"
    ensure_certs_present(server_certs_dir, cn="localhost", sans_csv="127.0.0.1,localhost")
    ensure_certs_present(wrong_certs_dir, cn="localhost", sans_csv="127.0.0.1,localhost")

    app = FastAPI()

    @app.get("/test")
    async def _test_endpoint() -> dict[str, str]:
        return {"status": "ok"}

    port = _free_port()

    # phaze-pv3kk: snapshot BEFORE `uvicorn.Config(...)`, which is the call that leaks --
    # see the note beside the restore in this fixture's `finally`. `Config.__init__` runs
    # `configure_logging()` itself, so a snapshot taken after construction records the
    # already-clobbered WARNING and restores nothing.
    _leaked_loggers = ("uvicorn", "uvicorn.error", "uvicorn.access")
    _saved_levels = {name: logging.getLogger(name).level for name in _leaked_loggers}

    config = uvicorn.Config(
        app,
        host="127.0.0.1",
        port=port,
        ssl_keyfile=str(server_certs_dir / "phaze-server.key"),
        ssl_certfile=str(server_certs_dir / "phaze-server.crt"),
        log_level="warning",
        lifespan="off",
    )
    server = uvicorn.Server(config)

    # phaze-pv3kk (the restore is in `finally` below; the snapshot is above the `Config` call).
    # `uvicorn.Config` applies uvicorn's LOGGING_CONFIG through
    # `logging.config.dictConfig` the moment it is constructed, which sets the PROCESS-GLOBAL
    # levels of the `uvicorn` / `uvicorn.error` / `uvicorn.access` loggers to `log_level` above
    # -- WARNING. Nothing ever puts them back. tests/conftest.py's autouse
    # `_route_structlog_through_stdlib` teardown resets structlog and clears the ROOT logger's
    # handlers, but it does not touch other loggers' LEVELS, so the WARNING outlives this module
    # for the rest of the pytest process.
    #
    # That was invisible for as long as nothing downstream of this file asserted on an INFO
    # record from one of those loggers -- and in the full suite's collection order, nothing does.
    # `tests/shared/core/test_logging_operational.py::test_foreign_stdlib_log_flows_through_configured_pipeline`
    # emits `logging.getLogger("uvicorn.error").info(...)` and asserts it renders; run that module
    # after this one and it fails with `StopIteration` on an empty capsys. Minimal reproducer,
    # measured 2026-08-25:
    #
    #     uv run pytest tests/agents/services/test_agent_client_tls.py \
    #                   tests/shared/core/test_logging_operational.py
    #     -> 1 failed, 7 passed  (each module alone: green)
    #
    # It surfaced while selecting `just check-fast`'s subset, because ANY subset reorders what
    # runs between a leak and the test sensitive to it. The general form is worth carrying:
    # **a suite that is green only in one collection order is green by coincidence** -- the
    # ordering is not a property anything asserts, so a new test file, a rename, or a subset
    # changes it. Containing the leak at its source is what makes the order irrelevant.
    #
    # This is the only `uvicorn.Config`/`Server` construction in the tree (`grep -rn` over
    # `tests/` and `src/phaze/`), so restoring here restores everywhere.
    server_task = asyncio.create_task(server.serve())

    await _wait_for_tcp("127.0.0.1", port, timeout=5.0)
    try:
        yield port, server_certs_dir, wrong_certs_dir
    finally:
        server.should_exit = True
        try:
            await asyncio.wait_for(server_task, timeout=5.0)
        except (TimeoutError, asyncio.CancelledError):
            server_task.cancel()
        for name, level in _saved_levels.items():
            logging.getLogger(name).setLevel(level)


@pytest.mark.asyncio
async def test_wrong_ca_raises_connect_error(tls_server: tuple[int, Path, Path]) -> None:
    """D-04 success criterion: the agent client built with the WRONG CA against a
    server presenting the RIGHT cert raises httpx.ConnectError on first request.

    Goes through :class:`PhazeAgentClient` with a CA PATH STRING -- the exact shape
    ``construct_agent_client`` hands it in production -- rather than constructing an
    ``ssl.SSLContext`` here. httpx 0.28 deprecated ``verify=<str>``, so phaze now maps the
    path to a context itself (``services/agent_client._resolve_verify``); a test that built
    its own context would exercise the mapping it is supposed to be checking exactly nowhere,
    and would keep passing if the production mapping were dropped or inverted.
    """
    port, _server_certs, wrong_certs = tls_server
    wrong_ca = str(wrong_certs / "phaze-ca.crt")
    client = PhazeAgentClient(base_url=f"https://127.0.0.1:{port}", token=_TEST_TOKEN, verify=wrong_ca)
    try:
        with pytest.raises(httpx.ConnectError):
            await client._client.get("/test")
    finally:
        await client.close()


@pytest.mark.asyncio
async def test_correct_ca_succeeds(tls_server: tuple[int, Path, Path]) -> None:
    """The same client with the CORRECT CA bundle path gets a 200 OK."""
    port, server_certs, _wrong_certs = tls_server
    correct_ca = str(server_certs / "phaze-ca.crt")
    client = PhazeAgentClient(base_url=f"https://127.0.0.1:{port}", token=_TEST_TOKEN, verify=correct_ca)
    try:
        response = await client._client.get("/test")
        assert response.status_code == 200
        assert response.json() == {"status": "ok"}
    finally:
        await client.close()


def test_resolve_verify_maps_each_accepted_shape(tmp_path: Path) -> None:
    """The three branches of the path -> context mapping, pinned separately from the TLS pair.

    The real-TLS tests above prove the FILE branch end to end. This one covers the two shapes
    they cannot reach without a second server: a directory (``capath``) and a non-string
    (``bool`` / an already-built context), which must pass through untouched so
    ``verify=True``'s certifi default and ``verify=False``'s bypass are unaffected.
    """
    ensure_certs_present(tmp_path, cn="localhost", sans_csv="127.0.0.1,localhost")

    assert isinstance(_resolve_verify(str(tmp_path / "phaze-ca.crt")), ssl.SSLContext)
    assert isinstance(_resolve_verify(str(tmp_path)), ssl.SSLContext)
    assert _resolve_verify(True) is True
    assert _resolve_verify(False) is False
    prebuilt = ssl.create_default_context()
    assert _resolve_verify(prebuilt) is prebuilt


def test_construct_agent_client_missing_ca_raises(tmp_path: Path) -> None:
    """D-03 fail-fast: construct_agent_client with a non-existent CA file
    raises RuntimeError("CA file empty or unreadable: ...").
    """
    missing_ca = tmp_path / "nonexistent.crt"
    cfg = AgentSettings(
        agent_api_url="https://127.0.0.1:9999",
        agent_token=SecretStr("phaze_agent_test-token-1234567890abcdef"),
        scan_roots=["/tmp"],  # noqa: S108  # test-only path
        agent_ca_file=str(missing_ca),
        queue_url="postgresql://phaze:phaze@app-server.example:5432/phaze",  # phaze-27myl
    )
    with pytest.raises(RuntimeError, match="CA file empty or unreadable"):
        construct_agent_client(cfg)


def test_construct_agent_client_empty_ca_raises(tmp_path: Path) -> None:
    """D-03 fail-fast: construct_agent_client with an empty CA file (size=0)
    also raises RuntimeError. Catches the case where the operator created
    the file but didn't populate it.
    """
    empty_ca = tmp_path / "empty.crt"
    empty_ca.write_bytes(b"")
    cfg = AgentSettings(
        agent_api_url="https://127.0.0.1:9999",
        agent_token=SecretStr("phaze_agent_test-token-1234567890abcdef"),
        scan_roots=["/tmp"],  # noqa: S108  # test-only path
        agent_ca_file=str(empty_ca),
        queue_url="postgresql://phaze:phaze@app-server.example:5432/phaze",  # phaze-27myl
    )
    with pytest.raises(RuntimeError, match="CA file empty or unreadable"):
        construct_agent_client(cfg)
