"""Real-TLS integration tests for PhazeAgentClient verify= wiring (Phase 29 D-04).

Stands up a real uvicorn server with a leaf cert generated by
``phaze.cert_bootstrap.ensure_certs_present`` and exercises the
``httpx.AsyncClient(verify=...)`` path against TWO independent CA bundles:

    1. wrong-CA  -> ``httpx.ConnectError`` (D-04 success criterion)
    2. correct-CA -> 200 OK response
    3. ``construct_agent_client(cfg)`` with a missing CA file
       -> ``RuntimeError("CA file empty or unreadable: ...")``

These tests intentionally do NOT use respx -- respx mocks at the httpx
transport layer below TLS, so it cannot exercise cert verification.
The trade-off is a slower test (real uvicorn boot + asyncio task) but
it is the only way to assert the rejection path that AUTH-02 promises.

The test is marked with ``pytest.mark.integration`` per
``[tool.pytest.ini_options] markers`` in pyproject.toml.
"""

from __future__ import annotations

import asyncio
import socket
from typing import TYPE_CHECKING

from fastapi import FastAPI
import httpx
from pydantic import SecretStr
import pytest
import uvicorn

from phaze.cert_bootstrap import ensure_certs_present
from phaze.config import AgentSettings
from phaze.tasks._shared.agent_bootstrap import construct_agent_client


if TYPE_CHECKING:
    from collections.abc import AsyncIterator
    from pathlib import Path


pytestmark = pytest.mark.integration


def _free_port() -> int:
    """Bind to port 0 to find an unused TCP port; release immediately."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return int(s.getsockname()[1])


async def _wait_for_tcp(host: str, port: int, timeout: float = 5.0) -> None:
    """Poll until a TCP connect to (host, port) succeeds or timeout elapses."""
    deadline = asyncio.get_running_loop().time() + timeout
    while asyncio.get_running_loop().time() < deadline:
        try:
            reader, writer = await asyncio.open_connection(host, port)
            writer.close()
            await writer.wait_closed()
        except (OSError, ConnectionRefusedError):
            await asyncio.sleep(0.05)
        else:
            del reader
            return
    msg = f"server did not start listening on {host}:{port} within {timeout}s"
    raise TimeoutError(msg)


@pytest.fixture
async def tls_server(tmp_path: Path) -> AsyncIterator[tuple[int, Path, Path]]:
    """Spin up a uvicorn server with a real TLS cert in tmp_path/server_certs.

    Yields ``(port, server_certs_dir, wrong_certs_dir)``:
        - ``port``: the bound port the server listens on
        - ``server_certs_dir``: dir holding ``phaze-ca.crt`` matching the
          server's leaf (the "correct" CA from the agent's POV)
        - ``wrong_certs_dir``: dir holding a DIFFERENT CA -- the agent's
          verify= path uses this to prove untrusted certs are rejected
    """
    server_certs_dir = tmp_path / "server_certs"
    wrong_certs_dir = tmp_path / "wrong_certs"
    ensure_certs_present(server_certs_dir, cn="localhost", sans_csv="127.0.0.1,localhost")
    ensure_certs_present(wrong_certs_dir, cn="localhost", sans_csv="127.0.0.1,localhost")

    app = FastAPI()

    @app.get("/test")
    async def _test_endpoint() -> dict[str, str]:
        return {"status": "ok"}

    port = _free_port()
    config = uvicorn.Config(
        app,
        host="127.0.0.1",
        port=port,
        ssl_keyfile=str(server_certs_dir / "phaze-server.key"),
        ssl_certfile=str(server_certs_dir / "phaze-server.crt"),
        log_level="warning",
        lifespan="off",
    )
    server = uvicorn.Server(config)
    server_task = asyncio.create_task(server.serve())

    await _wait_for_tcp("127.0.0.1", port, timeout=5.0)
    try:
        yield port, server_certs_dir, wrong_certs_dir
    finally:
        server.should_exit = True
        try:
            await asyncio.wait_for(server_task, timeout=5.0)
        except (TimeoutError, asyncio.CancelledError):
            server_task.cancel()


@pytest.mark.asyncio
async def test_wrong_ca_raises_connect_error(tls_server: tuple[int, Path, Path]) -> None:
    """D-04 success criterion: httpx.AsyncClient with the WRONG CA against a
    server presenting the RIGHT cert raises httpx.ConnectError on first request.
    """
    port, _server_certs, wrong_certs = tls_server
    wrong_ca = str(wrong_certs / "phaze-ca.crt")
    async with httpx.AsyncClient(base_url=f"https://127.0.0.1:{port}", verify=wrong_ca) as client:
        with pytest.raises(httpx.ConnectError):
            await client.get("/test")


@pytest.mark.asyncio
async def test_correct_ca_succeeds(tls_server: tuple[int, Path, Path]) -> None:
    """The same client with the CORRECT CA bundle gets a 200 OK."""
    port, server_certs, _wrong_certs = tls_server
    correct_ca = str(server_certs / "phaze-ca.crt")
    async with httpx.AsyncClient(base_url=f"https://127.0.0.1:{port}", verify=correct_ca) as client:
        response = await client.get("/test")
        assert response.status_code == 200
        assert response.json() == {"status": "ok"}


def test_construct_agent_client_missing_ca_raises(tmp_path: Path) -> None:
    """D-03 fail-fast: construct_agent_client with a non-existent CA file
    raises RuntimeError("CA file empty or unreadable: ...").
    """
    missing_ca = tmp_path / "nonexistent.crt"
    cfg = AgentSettings(
        agent_api_url="https://127.0.0.1:9999",
        agent_token=SecretStr("phaze_agent_test-token-1234567890abcdef"),
        scan_roots=["/tmp"],  # noqa: S108  # test-only path
        agent_ca_file=str(missing_ca),
    )
    with pytest.raises(RuntimeError, match="CA file empty or unreadable"):
        construct_agent_client(cfg)


def test_construct_agent_client_empty_ca_raises(tmp_path: Path) -> None:
    """D-03 fail-fast: construct_agent_client with an empty CA file (size=0)
    also raises RuntimeError. Catches the case where the operator created
    the file but didn't populate it.
    """
    empty_ca = tmp_path / "empty.crt"
    empty_ca.write_bytes(b"")
    cfg = AgentSettings(
        agent_api_url="https://127.0.0.1:9999",
        agent_token=SecretStr("phaze_agent_test-token-1234567890abcdef"),
        scan_roots=["/tmp"],  # noqa: S108  # test-only path
        agent_ca_file=str(empty_ca),
    )
    with pytest.raises(RuntimeError, match="CA file empty or unreadable"):
        construct_agent_client(cfg)
