"""Tests for CUE sheet generation service."""

from __future__ import annotations

from pathlib import Path

from phaze.services.cue_generator import (
    CueTrackData,
    generate_cue_content,
    next_cue_path,
    parse_timestamp_string,
    seconds_to_cue_timestamp,
    write_cue_file,
)


class TestSecondsToTimestamp:
    """Test CUE timestamp conversion at 75fps."""

    def test_zero(self):
        assert seconds_to_cue_timestamp(0.0) == "00:00:00"

    def test_half_second(self):
        # 0.5s * 75 = 37.5, int = 37 frames
        assert seconds_to_cue_timestamp(0.5) == "00:00:37"

    def test_five_and_half_seconds(self):
        # 5.5 * 75 = 412.5 -> 412 frames
        # 412 % 75 = 37 frames, 412 // 75 = 5 secs
        # 5 // 60 = 0 min, 5 % 60 = 5 sec
        assert seconds_to_cue_timestamp(5.5) == "00:05:37"

    def test_mixed_minutes_seconds(self):
        # 332.45 * 75 = 24933.75 -> 24933 total frames
        # 24933 % 75 = 33 frames
        # 24933 // 75 = 332 secs -> 5 min 32 sec
        assert seconds_to_cue_timestamp(332.45) == "05:32:33"

    def test_over_60_minutes(self):
        # 3661.0 * 75 = 274575 frames
        # 274575 % 75 = 0 frames
        # 274575 // 75 = 3661 secs -> 61 min 1 sec
        assert seconds_to_cue_timestamp(3661.0) == "61:01:00"

    def test_frames_never_reach_75(self):
        # Test edge: 0.99333... seconds -> 74.5 frames -> 74
        result = seconds_to_cue_timestamp(0.99333333)
        frames = int(result.split(":")[2])
        assert frames < 75

    def test_exact_one_minute(self):
        assert seconds_to_cue_timestamp(60.0) == "01:00:00"

    def test_exact_one_second(self):
        assert seconds_to_cue_timestamp(1.0) == "00:01:00"

    def test_max_frame_value(self):
        # 74/75 of a second = 0.98666... -> 74 frames exactly
        result = seconds_to_cue_timestamp(74 / 75)
        assert result == "00:00:74"


class TestParseTimestampString:
    """Test timestamp string parsing."""

    def test_none_returns_none(self):
        assert parse_timestamp_string(None) is None

    def test_hh_mm_ss(self):
        assert parse_timestamp_string("1:30:00") == 5400.0

    def test_mm_ss(self):
        assert parse_timestamp_string("5:32") == 332.0

    def test_raw_seconds_float(self):
        assert parse_timestamp_string("332.45") == 332.45

    def test_raw_seconds_integer(self):
        assert parse_timestamp_string("60") == 60.0

    def test_zero(self):
        assert parse_timestamp_string("0:00") == 0.0

    def test_long_set_hh_mm_ss(self):
        # 2:15:30 = 2*3600 + 15*60 + 30 = 8130
        assert parse_timestamp_string("2:15:30") == 8130.0


class TestGenerateCueContent:
    """Test CUE content string generation."""

    def test_basic_generation(self):
        tracks = [
            CueTrackData(position=1, title="First Track", artist="Artist A", timestamp_seconds=0.0),
            CueTrackData(position=2, title="Second Track", artist="Artist B", timestamp_seconds=332.45),
        ]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        lines = content.strip().split("\n")

        assert lines[0] == 'REM COMMENT "Generated by Phaze"'
        assert lines[1] == 'FILE "test.mp3" MP3'
        assert lines[2] == "  TRACK 01 AUDIO"
        assert '    TITLE "First Track"' in content
        assert '    PERFORMER "Artist A"' in content
        assert "    INDEX 01 00:00:00" in content
        assert "  TRACK 02 AUDIO" in content
        assert '    TITLE "Second Track"' in content
        assert "    INDEX 01 05:32:33" in content

    def test_tracks_ordered_by_position(self):
        tracks = [
            CueTrackData(position=3, title="Third", artist=None, timestamp_seconds=200.0),
            CueTrackData(position=1, title="First", artist=None, timestamp_seconds=0.0),
            CueTrackData(position=2, title="Second", artist=None, timestamp_seconds=100.0),
        ]
        content = generate_cue_content("audio.wav", "wav", tracks)
        lines = content.strip().split("\n")

        # Find TRACK lines and verify order
        track_lines = [line for line in lines if "TRACK" in line and "AUDIO" in line]
        assert len(track_lines) == 3
        assert "TRACK 01" in track_lines[0]
        assert "TRACK 02" in track_lines[1]
        assert "TRACK 03" in track_lines[2]

    def test_tracks_without_timestamp_omitted(self):
        tracks = [
            CueTrackData(position=1, title="Has Time", artist=None, timestamp_seconds=0.0),
            CueTrackData(position=2, title="No Time", artist=None, timestamp_seconds=None),
            CueTrackData(position=3, title="Has Time Too", artist=None, timestamp_seconds=60.0),
        ]
        content = generate_cue_content("audio.mp3", "mp3", tracks)
        assert "No Time" not in content
        assert "TRACK 01" in content
        assert "TRACK 02" in content
        # Track numbering is sequential after filtering, not based on position
        assert "TRACK 03" not in content

    def test_file_type_mp3(self):
        content = generate_cue_content("test.mp3", "mp3", [])
        assert 'FILE "test.mp3" MP3' in content

    def test_file_type_wav(self):
        content = generate_cue_content("test.wav", "wav", [])
        assert 'FILE "test.wav" WAVE' in content

    def test_file_type_aiff(self):
        content = generate_cue_content("test.aiff", "aiff", [])
        assert 'FILE "test.aiff" AIFF' in content

    def test_file_type_flac(self):
        content = generate_cue_content("test.flac", "flac", [])
        assert 'FILE "test.flac" WAVE' in content

    def test_file_type_ogg(self):
        content = generate_cue_content("test.ogg", "ogg", [])
        assert 'FILE "test.ogg" WAVE' in content

    def test_file_type_m4a(self):
        content = generate_cue_content("test.m4a", "m4a", [])
        assert 'FILE "test.m4a" WAVE' in content

    def test_file_type_opus(self):
        content = generate_cue_content("test.opus", "opus", [])
        assert 'FILE "test.opus" WAVE' in content

    def test_file_type_unknown_defaults_wave(self):
        content = generate_cue_content("test.xyz", "xyz", [])
        assert 'FILE "test.xyz" WAVE' in content

    def test_double_quotes_stripped_from_filename(self):
        content = generate_cue_content('file"with"quotes.mp3', "mp3", [])
        assert 'FILE "filewithquotes.mp3" MP3' in content

    def test_trailing_newline(self):
        content = generate_cue_content("test.mp3", "mp3", [])
        assert content.endswith("\n")

    def test_no_artist_or_title(self):
        tracks = [
            CueTrackData(position=1, title=None, artist=None, timestamp_seconds=0.0),
        ]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        assert "TITLE" not in content
        assert "PERFORMER" not in content
        assert "INDEX 01 00:00:00" in content

    def test_case_insensitive_file_type(self):
        content = generate_cue_content("test.mp3", "MP3", [])
        assert 'FILE "test.mp3" MP3' in content


class TestDiscogRem:
    """Test Discogs REM comment generation."""

    def test_full_discogs_metadata(self):
        tracks = [
            CueTrackData(
                position=1,
                title="Track One",
                artist="Artist",
                timestamp_seconds=0.0,
                genre="House",
                label="Defected Records",
                year=2023,
            ),
        ]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        assert '    REM GENRE "House"' in content
        assert '    REM LABEL "Defected Records"' in content
        assert '    REM YEAR "2023"' in content

    def test_no_discogs_metadata(self):
        tracks = [
            CueTrackData(position=1, title="Track", artist="Artist", timestamp_seconds=0.0),
        ]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        assert "REM GENRE" not in content
        assert "REM LABEL" not in content
        assert "REM YEAR" not in content

    def test_partial_discogs_metadata(self):
        tracks = [
            CueTrackData(
                position=1,
                title="Track",
                artist="Artist",
                timestamp_seconds=0.0,
                genre="Techno",
                label=None,
                year=None,
            ),
        ]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        assert '    REM GENRE "Techno"' in content
        assert "REM LABEL" not in content
        assert "REM YEAR" not in content

    def test_rem_order_before_title(self):
        tracks = [
            CueTrackData(
                position=1,
                title="Track",
                artist="Artist",
                timestamp_seconds=0.0,
                genre="House",
                label="Label",
                year=2023,
            ),
        ]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        lines = content.strip().split("\n")
        # Find REM and TITLE line indices
        rem_genre_idx = next(i for i, l in enumerate(lines) if "REM GENRE" in l)
        title_idx = next(i for i, l in enumerate(lines) if "TITLE" in l)
        assert rem_genre_idx < title_idx

    def test_mixed_tracks_with_and_without_discogs(self):
        tracks = [
            CueTrackData(
                position=1,
                title="Linked",
                artist="A",
                timestamp_seconds=0.0,
                genre="House",
                label="Label",
                year=2023,
            ),
            CueTrackData(
                position=2,
                title="Unlinked",
                artist="B",
                timestamp_seconds=60.0,
            ),
        ]
        content = generate_cue_content("test.mp3", "mp3", tracks)
        lines = content.strip().split("\n")
        # Track 1 should have REM lines, Track 2 should not
        track2_start = next(i for i, l in enumerate(lines) if "TRACK 02" in l)
        track2_lines = lines[track2_start:]
        track2_block = "\n".join(track2_lines)
        assert "REM GENRE" not in track2_block


class TestNextCuePath:
    """Test version suffix naming for CUE files."""

    def test_first_cue_no_existing(self, tmp_path):
        audio = tmp_path / "audio.mp3"
        audio.touch()
        result = next_cue_path(audio)
        assert result == tmp_path / "audio.cue"

    def test_second_cue_when_base_exists(self, tmp_path):
        audio = tmp_path / "audio.mp3"
        audio.touch()
        (tmp_path / "audio.cue").touch()
        result = next_cue_path(audio)
        assert result == tmp_path / "audio.v2.cue"

    def test_third_cue_when_base_and_v2_exist(self, tmp_path):
        audio = tmp_path / "audio.mp3"
        audio.touch()
        (tmp_path / "audio.cue").touch()
        (tmp_path / "audio.v2.cue").touch()
        result = next_cue_path(audio)
        assert result == tmp_path / "audio.v3.cue"

    def test_gap_in_versions(self, tmp_path):
        audio = tmp_path / "audio.mp3"
        audio.touch()
        (tmp_path / "audio.cue").touch()
        (tmp_path / "audio.v3.cue").touch()
        # v2 missing, but max is 3 -> next is v4
        result = next_cue_path(audio)
        assert result == tmp_path / "audio.v4.cue"


class TestWriteCueFile:
    """Test CUE file writing with UTF-8 BOM."""

    def test_written_file_has_bom(self, tmp_path):
        audio = tmp_path / "test.mp3"
        audio.touch()
        content = 'REM COMMENT "Generated by Phaze"\nFILE "test.mp3" MP3\n'
        result = write_cue_file(content, audio)
        raw = result.read_bytes()
        assert raw[:3] == b"\xef\xbb\xbf"

    def test_content_matches(self, tmp_path):
        audio = tmp_path / "test.mp3"
        audio.touch()
        content = 'REM COMMENT "Generated by Phaze"\nFILE "test.mp3" MP3\n'
        result = write_cue_file(content, audio)
        # Read back, stripping BOM
        text = result.read_text(encoding="utf-8-sig")
        assert text == content

    def test_returns_path(self, tmp_path):
        audio = tmp_path / "test.mp3"
        audio.touch()
        result = write_cue_file("content\n", audio)
        assert isinstance(result, Path)
        assert result.exists()

    def test_version_increment_on_rewrite(self, tmp_path):
        audio = tmp_path / "test.mp3"
        audio.touch()
        first = write_cue_file("v1\n", audio)
        assert first.name == "test.cue"
        second = write_cue_file("v2\n", audio)
        assert second.name == "test.v2.cue"
