---
name: Code Quality

on:
  workflow_call:

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: "\U0001F4E5 Checkout code"
        uses: actions/checkout@v4

      - name: "\U0001F4E6 Install uv"
        uses: astral-sh/setup-uv@v4

      - name: "\U0001F40D Set up Python 3.13"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: "\U0001F4E6 Install dependencies"
        run: uv sync

      - name: "\U0001F9F9 Run pre-commit hooks"
        uses: pre-commit/action@v3.0.1
